#!/bin/bash
shopt -s nocasematch
cd $(dirname $0)

AGENT="$1"
EXT_LEDGER="$2"

# for initialising with either local von or public von network
if [ $# -eq 1 ];  then
  LEDGER_URL="http://greenlight.bcovrin.vonx.io"
  echo "using public BCGov test network"
else
  echo "Using local development ledger. An indy ledger needs to be running locally on port 9000."
  LEDGER_URL="http://${DOCKERHOST}:9000"
fi

shift
DOCKER_NET="bridge"

#set ports
if [ "$AGENT" = "bank" ]; then
  AGENT_MODULE="bank"
  AGENT_PORT=7030
  AGENT_PORT_RANGE=7030-7033
elif [ "$AGENT" = "vendor" ]; then
  AGENT_MODULE="vendor"
  AGENT_PORT=7040
  AGENT_PORT_RANGE=7040-7043
elif [ "$AGENT" = "shipper" ]; then
  AGENT_MODULE="shipper"
  AGENT_PORT=7050
  AGENT_PORT_RANGE=7050-7053
elif [ "$AGENT" = "user" ]; then
  AGENT_MODULE="user"
  AGENT_PORT=7060
  AGENT_PORT_RANGE=7060-7063
else
  exit 1
fi

#build as per dockerfile requirements
docker build -q -t transaction-demo -f ../docker/Dockerfile.shop .. || exit 1

DOCKERHOST=`docker run --rm --net=host eclipse/che-ip`
export RUNMODE="docker"

echo "Host is: {$DOCKERHOST}"
DOCKER_ENV="-e RUNMODE=${RUNMODE} -e DOCKERHOST=${DOCKERHOST}"
DOCKER_ENV="${DOCKER_ENV} -e AGENT_PORT=${AGENT_PORT}"
DOCKER_ENV="${DOCKER_ENV} -e ROLE=${AGENT_MODULE}"

echo "LEDGER_URL: ${LEDGER_URL}"
GENESIS_URL="${LEDGER_URL}/genesis"
DOCKER_ENV="${DOCKER_ENV} -e LEDGER_URL=${LEDGER_URL}"
DOCKER_ENV="${DOCKER_ENV} -e GENESIS_URL=${GENESIS_URL}"

if ! [ -z "$AGENT_ENDPOINT" ]; then
  DOCKER_ENV="${DOCKER_ENV} -e AGENT_ENDPOINT=${AGENT_ENDPOINT}"
fi

DOCKER=${DOCKER:-docker}

echo "working directory: $(pwd)"

$DOCKER run --name $AGENT --rm -it ${DOCKER_OPTS} --network=${DOCKER_NET} -p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE \
  -v "/$(pwd)/:/home/indy/shop"  $DOCKER_ENV transaction-demo $AGENT_MODULE --port $AGENT_PORT
